FROM php:fpm-alpine

# 2023.02.21
# Alpine 3.17
# PHP 8.2.3
# supercronic v0.2.1
# This image can use for PHP-FPM or cronjob

ENV JOB_ONLY="No"
ENV CRON_ONLY="No"

ENV SUPERCRONIC_VERSION="v0.2.1" \
    SUPERCRONIC=supercronic-linux-amd64 \
    SUPERCRONIC_SHA1SUM=d7f4c0886eb85249ad05ed592902fa6865bb9d70

ENV SUPERCRONIC_URL=https://github.com/aptible/supercronic/releases/download/$SUPERCRONIC_VERSION/$SUPERCRONIC

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && sync && \
    install-php-extensions bcmath calendar exif gd imagick intl memcached mongodb mysqli opcache pdo_mysql pdo_pgsql pgsql redis soap tidy uuid xdebug xsl zip

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

# Install Composer
RUN install -d -m 0755 -o www-data -g www-data /.composer &&\
    curl -sS https://getcomposer.org/installer | \
        php -- --install-dir=/usr/local/bin \
               --filename=composer &&\
    chown -R www-data:www-data /.composer


# disable xdebug
RUN install -d -m 0755 -o www-data -g www-data /p /p/xdebug /p/others && \
    mv /usr/local/etc/php/conf.d/*xdebug.ini /p/xdebug/;

COPY ./server/php/100-others.ini /p/others/100-others.ini

# enable some custom config for php
RUN chown -R www-data:www-data /p

# install tools: git, nano
RUN apk --update add --no-cache git openssh libssl1.1 nano runit && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

# integrate runit
COPY ./server/runit/boot.sh /sbin/boot.sh
RUN sed -i 's/\r//g' /sbin/boot.sh && chmod +x /sbin/boot.sh

# supercronic for cronjob
RUN curl -fsSLO "$SUPERCRONIC_URL" \
    && echo "${SUPERCRONIC_SHA1SUM}  ${SUPERCRONIC}" | sha1sum -c - \
    && chmod +x "$SUPERCRONIC" \
    && mv "$SUPERCRONIC" "/usr/local/bin/${SUPERCRONIC}" \
    && ln -s "/usr/local/bin/${SUPERCRONIC}" /usr/local/bin/supercronic

COPY ./server/crontabs/lt-crons /etc/crontabs/lt-crons

# runit services config for fpm
RUN mkdir /etc/service/fpm
COPY ./server/runit/php-fpm /etc/service/fpm/run
RUN sed -i 's/\r//g' /etc/service/fpm/run && chmod +x /etc/service/fpm/run


# runit config service config for supercronic
RUN mkdir /etc/service/supercronic && touch /etc/service/supercronic/down
COPY ./server/runit/supercronic /etc/service/supercronic/run
RUN sed -i 's/\r//g' /etc/service/supercronic/run && chmod +x /etc/service/supercronic/run

WORKDIR /usr/www/src

STOPSIGNAL SIGQUIT
EXPOSE 9000

CMD [ "/sbin/boot.sh" ]
