version: "3.3"

# Ref https://docs.docker.com/compose/compose-file/

services:
  redis:
    image: 'redis:alpine'
    container_name: redis
    sysctls:
      - net.core.somaxconn=511
    volumes:
      - ./server/redis/rc.local:/etc/rc.local'
      - ./server/redis/data:/data'
    networks:
      - backend
    expose:
      - '6379'
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.125'
          memory: 50M
        reservations:
          cpus: '0.125'
          memory: 20M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s


  nginx:
    image: 'laptrinhcomvn/ltpro_nginx:latest'
    container_name: nginx
    environment:
      - ENABLE_IPV6=true
      - TZ=Asia/Ho_Chi_Minh
    working_dir: /usr/www/src
    networks:
      - backend
      - frontend
    restart: always
    depends_on:
      - phpfpm
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/usr/www/src
      - './nginx/sites-enabled:/etc/nginx/sites-enabled'

  phpfpm:
    image: 'laptrinhcomvn/ltpro_phpfpm:latest'
    container_name: phpfpm
    environment:
      - ENABLE_IPV6=true
      - TZ=Asia/Ho_Chi_Minh
    working_dir: /usr/www/src
    networks:
      - backend
    restart: always
    depends_on:
      - redis
      - mysql
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 64M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      #- './server/php/100-others-debug.ini:/p/others/100-others.ini' #debug
      - '.src:/usr/www/src'

      
  jobs:
    image: 'laptrinhcomvn/ltpro_phpfpm:latest'
    container_name: jobs
    environment:
      - ENABLE_IPV6=true
      - TZ=Asia/Ho_Chi_Minh
      - JOB_ONLY=1
    working_dir: /usr/www/src
    networks:
      - backend
    depends_on:
      - mysql
    volumes:
      #- ./runit/my_service:/etc/service/my_service # read runit docs
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 64M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  crons:
    image: 'laptrinhcomvn/ltpro_phpfpm:latest'
    container_name: crons
    environment:
      - ENABLE_IPV6=true
      - TZ=Asia/Ho_Chi_Minh
      - CRON_ONLY=1
    working_dir: /usr/www/src
    networks:
      - backend
    depends_on:
      - mysql
    volumes:
      #- ./server/crontabs/lt-crons:/etc/crontabs/lt-crons # read supercronic đocs
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 64M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  
  mysql:
    image: 'mysql:8.0.21'
    command: '--default-authentication-plugin=mysql_native_password'
    container_name: mysql
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - MYSQL_ROOT_PASSWORD=12345678
    volumes:
      - ./server/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./server/mysql/data:/var/lib/mysql'
    networks:
      - backend
    restart: always
    ports:
      - '3306:3306'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 768M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  backend: null
  frontend: null